### ISSUE TITLE
Cross design spreadsheet with preselected columns (variables) (in browser)

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#103]

**Comment by remomueller** [comment]
@mrueschman, any thoughts on the need for this type of feature? (Or how it would look to have variables from different designs looking?) If not, we can close this issue.

**Comment by mrueschman** [comment]
This is very much in the spirit of how REDCap does Reports. Add an arbitrary number of fields from any design(s)/instrument(s) and then display them with subject IDs for the rows and the fields of interest for the columns. There are further filters one can add based on Events/Timepoints, so a longitudinal project with variables separated across events can get a little strange looking (like below). (Slice would obviously face similar issues.)

<img width="843" alt="screen shot 2018-05-23 at 3 12 16 pm" src="https://user-images.githubusercontent.com/707167/40446003-c5636754-5e9b-11e8-88da-edeba1000c51.png">

<img width="776" alt="screen shot 2018-05-23 at 3 12 04 pm" src="https://user-images.githubusercontent.com/707167/40446095-119b5726-5e9c-11e8-857e-1b9f3e9396f7.png">

We haven't "needed" it for a long time so we can probably close this issue. Maybe some similar ideas will arise if we look more closely at Reports at some point. I could see some tune-ups to the Design Overview reports and potential elimination of the Advanced report builder at some point.

**Comment by remomueller** [comment]
Removing the advanced report builder would provide the ability to lift out a large section of internal code dedicated to those types of filters, however while complex, the code hasn't required many changes either.

**Comment by remomueller** [comment]
Ok, so we'll remove the advanced report build to start and then create a new issue when we add in the compact multi-subject view  (+ variables) type of report. Closing this issue for now, thanks!
