### ISSUE TITLE
Allow for preset values in grid variables

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#113]
For instance, if you have a grid that increments by Day Number (1 row per day), it would be nice to have the Day Number variable be pre-filled (e.g. 1, 2, 3, 4). Thus, you might need to set an initial preset and a value to increment for each subsequent row.

**Comment by remomueller** [comment]
After much discussion, this is mainly needed as a visual indicator, and may be added when grids are updated in the future. Closing this issue.
