### ISSUE TITLE
Remove Double Data Entry implementation

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#128]
The `get_response` method in the `Sheet` model is confusing and redundant.

Update: It looks like it is only referenced from `app/views/designs/master_verification.html.haml` and `app/views/sheets/verification_report.html.haml`.

**Comment by remomueller** [comment]
@mrueschman, we may want to consider removing the current iteration of double-data entry and create a better solution for it in the future. (As you mentioned more role-based).

**Comment by mrueschman** [comment]
Sounds good to me.
