### ISSUE TITLE
Having a variable in project called 'site' will break SAS import

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#149]
Presumably this would happen with other "Design and Subject Variables" as well. In OPTIMAL-HF there was a variable called `site`, which then conflicted with the `site` that is stored alongside every subject/sheet. You essentially then have columns with duplicate variable names.

Here's what happens in SAS. The fix was to rename the instance of the `site` variable that was being used on a single Design. Perhaps in the future there should just be reserved names that can't be used by the user when creating new variables (e.g. `site`, `subject`, etc.)

```
9449!  firstobs=2 ;
9450
9451    /* Design and Subject Variables */
9452    informat sheet_id             best32.   ;   * Sheet ID ;
9453    informat name                 $500.     ;   * Design name ;
9454    informat description          $5000.    ;   * Design description ;
9455    informat sheet_creation_date  yymmdd10. ;   * Sheet creation date ;
9456    informat project              $500.     ;   * Project name ;
9457    informat site                 $500.     ;   * Subject site name ;
9458    informat subject              $100.     ;   * Subject code ;
9459    informat acrostic             $100.     ;   * Subject acrostic ;
9460    informat status               $10.      ;   * Subject status ;
9461    informat creator              $100.     ;   * Sheet creator ;
9462    informat schedule_name        $500.     ;   * Schedule name ;
9463    informat event_name           $500.     ;   * Event name ;
9464
9465    /* Sheet Variables */
9466    informat subject_id $500. ;
9467    informat date yymmdd10. ;
9468    informat staff_id1 $500. ;
9469    informat site best32. ;
                      -------
                      48
ERROR 48-59: The informat $BEST was not found or could not be loaded.

9470    informat this_report_is_the best32. ;
```

**Comment by remomueller** [comment]
I'm including this in v0.31.0, I'll be adding the `_` underscore in front of these variables as it's allowed by SAS, and it's specifically NOT allowed in Slice (for Slice variables), so this should work quite well.

**Comment by remomueller** [comment]
@mrueschman, do we need a similar issue for the R export as well? And if so, does R allow variables to start with an `_` underscore?

**Comment by mrueschman** [comment]
At a glance it seems like "_" can't start a variable name in R. I'll look at how the R import is currently working and if we need a change.

**Comment by mrueschman** [comment]
The R import seems to adequately handle duplicate column names on the import. It will rename the duplicate to something like "Site.1". I suppose, then, that we don't need a similar issue for the R export -- it can be left as is.
