### ISSUE TITLE
When transferring ownership of a project, the new owner should no longer be listed as an editor on the project

### ISSUE THREAD

**Issue by mcailler** [remomueller/slice#179]
It seems redundant to list someone separately as an owner and an editor, given that the owner in theory has all the privileges of an editor, and that the original project owner is not double listed by default.
![slice ownership](https://cloud.githubusercontent.com/assets/1759957/5115600/bde4eb38-7010-11e4-9e52-e7b621484563.jpg)

**Comment by remomueller** [comment]
These are different roles and responsibilities. You can manually remove the user as Project Editor if so desired.
