### ISSUE TITLE
Update Slice Subject Reports to take advantage of 'schedules' feature

### ISSUE THREAD

**Issue by mcailler** [remomueller/slice#182]
Currently, the Slice Subject overview report is quite long (Optimal-HF is 22 rows wide); it would be useful, and more compact if Slice was able to use schedules in lieu of individual designs to display this information.

In theory, I would envision it being subjects down the side and schedules or events at the top, with each subject having either a percent completed of a given design (without even taking into account individual sheet completion percentage) or having just a fraction of the forms completed

| Subject | Pre-Screening | Screening | Randomized | HLSE | HLSE-O | HLSE-ASV | HLSE-PAP |
|-----------|--------------------|---------------|----------------|---------|:------------:|---------------|---------------|
| 293478 | 2/2 | 2/2 | 8/19 | N/A | - | 3/4 | N/A|

**Comment by remomueller** [comment]
Add `position` to schedules to allow ordering of schedules.

**Comment by remomueller** [comment]
Most reports should have a new `application-full.html.haml` layout to better make use of screen real-estate.

**Comment by mcailler** [comment]
Counts should be based on existing sheets only rather than sheets that are at 100%
