### ISSUE TITLE
On subject show page, allow schedules to be re-ordered

### ISSUE THREAD

**Issue by mcailler** [remomueller/slice#186]
Currently, when you add a schedule, it defaults to adding the schedule to the bottom of the list - it would be more atheistically pleasing to be able to rearrange them into a logical order

**Comment by remomueller** [comment]
Add `position:integer` to Schedule model.

**Comment by remomueller** [comment]
@mcailler is this issue resolved with the new redesign of the subject pages? Thanks!

**Comment by remomueller** [comment]
Subject events are now ordered by the event date, closing issue.
