### ISSUE TITLE
Add Row potentially not working on IE9

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#188]
Look into Add Row in IE9 to see if it's throwing errors (may need JS compatibility library added).

**Comment by remomueller** [comment]
@mcailler is this related to #193?

**Comment by remomueller** [comment]
@mrueschman can you test this out at some point to see if it's still an issue?

**Comment by mrueschman** [comment]
Looks to be working. Probably related to #193 as mentioned earlier. Closing issue.
