### ISSUE TITLE
Improve flow of inviting and signing up new users

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#189]
It seems like, without fail, whenever I try to invite someone (new user) to a project they get tripped up by the 1) sign up and then 2) go back to email to click invitation link process. Users often get signed up, approved, then don't have the realization to go back to the invitation email again to click it. Hence, it requires my intervention and guidance somewhere along the way.

If we turned off the need to approve new users (on sleepepi/slice) could we eliminate this disconnect and difficulty?

**Comment by remomueller** [comment]
Potentially, it may also be caused by the multiple routes in which one can sign up, which eventually loses the friendly forward link, and just goes to the home page.

**Comment by mrueschman** [comment]
I simulated the sign-up for a new user on the demo site (no admin approval needed) and it worked fairly seamlessly. Perhaps, then, it is the approval step that is causing most of the confusion. I guess we could 1) ask people to sign-up first before sending project invitation and/or 2) eliminate the approval requirement on our primary Slice installation.

**Comment by mrueschman** [comment]
We should make this Better in the nearer-term (i.e. for PATS).

@remomueller @mcailler

**Comment by remomueller** [comment]
I'll make it so the invite is stored and persisted in the user session, and on login or registration, the user will get a notification of having been added to the project.
