### ISSUE TITLE
Allow sheets to generate a URL to share

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#195]
Right now when public surveys are submitted a subject is created with a long string of nonsensical characters (e.g. `240736856e585`).

For some projects these surveys might be coming from subjects with actual codes that exist elsewhere in the system (e.g. from screening, baseline visits). Sheets can have the IDs renamed, but this is tedious and then the nonsensical subjects still exist in the system.

Ideally, the survey sheet would automatically be associated with the proper subject ID upon submission. An option:

- A subject ID variable (of some sort? a special variable type?) is present on the Design and, when entered by the subject, this is what is used when saving the sheet. In this case it would probably be useful to have the subject enter the ID twice for confirmation purposes.

**Comment by remomueller** [comment]
For reference, this will be a project-wide setting, `subject_codes_on_public_surveys_enabled`

**Comment by mrueschman** [comment]
Would probably be better to have surveys sent to people by email with unique URLs. This would be good because subjects would not have to enter their own ID (prone to mistakes).
