### ISSUE TITLE
Dropdown boxes aren't vertically centered

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#232]
![image](https://cloud.githubusercontent.com/assets/707167/8836726/8eb72858-3090-11e5-838b-3d2a8ce49bdf.png)

The "J" in Jackson is cutoff and Emily's name is quite low.

Intriguingly, dropdowns in grids appear to be centered!

![image](https://cloud.githubusercontent.com/assets/707167/8836738/a643fb90-3090-11e5-8a74-a46668fb6811.png)

**Comment by remomueller** [comment]
Thanks, I'll take a look into what's causing this, may be due to a line-height being off after we changed the default font size.
