### ISSUE TITLE
Create new date format dd-mmm-yyyy

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#237]
For upcoming trials, it might be nice to have dd-mmm-yyyy format. E.g. 28-JUL-2015

Use a dropdown for the 3 letter months.

**Comment by remomueller** [comment]
Will be done, should be fairly straightforward to implement. Thanks!

**Comment by mrueschman** [comment]
Looked on staging, nice! @mcailler for his reference if he continues to work on any trials that use date formats such as this.
