### ISSUE TITLE
Make study overview report (dashboard) with nifty visualizations

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#242]
Somewhat akin to the "Overview" for a given design, it might be nice to have some sort of dashboard that describes/summarizes what is in a given project.

Broken down overall and by site:

1. Number of subjects
2. Number of subjects randomized (to a given scheme; usually just a single scheme)
3. Randomization accrual over time (total randomizations on Y-axis; time on X-axis)

**Comment by remomueller** [comment]
Thanks @mrueschman, should this also be by site in any way?

**Comment by mrueschman** [comment]
Yeah, that's why I said "broken down overall and **by site**". :laughing: 

One tricky bit might be whether the sites have individual (different) "goals". We obviously have a target randomization goal (e.g. 460 in PATS), but it's doubtful that the quota will be filled equally across the 5 sites.

**Comment by remomueller** [comment]
Perhaps they can be given a "contribution %" or something like that to compare against each other. Completely missed the "by site" portion of it. You sure you didn't just edit that in afterwards? :wink:

**Comment by mrueschman** [comment]
Try adding some of these things to the Reports page to start.
