### ISSUE TITLE
Create CSV export for Adverse Event Reports

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#266]

**Comment by remomueller** [comment]
@mrueschman, I've pushed a version of this to staging, we can probably iterate a bit further to see if additional fields are required in the export. Thanks!

**Comment by mrueschman** [comment]
Nice. Data from the associated AE Designs will also be of interest, so it might be worth considering whether to somehow include it with this export or to figure out elsewhere how these data sources will be linked.

**Comment by remomueller** [comment]
Moving this to 0.32.0 for additional improvements to export

**Comment by remomueller** [comment]
Will include CSV Labeled by default with this export.
