### ISSUE TITLE
Provide better validation error if a "generic" file upload does not fall have an extension that is whitelisted

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#274]
For files that aren't `jpg` `jpeg` `gif` `png` `doc` `docx` `pdf` `xls` `xlsx` `rtf`, make sure that saving a sheet provides a warning or error that the file won't be saved.

**Comment by remomueller** [comment]
@mrueschman Can you think of any other file types we may want to allow by default? XML? (PSG annotations?), CSVs?

**Comment by mrueschman** [comment]
Sure, maybe XML, CSV, TXT.

**Comment by remomueller** [comment]
Ok thanks

**Comment by mrueschman** [comment]
File uploads have been changed a bit to allow additional file types (e.g. .ABP for ambulatory blood pressure) to be uploaded on sheets. Closing.
