### ISSUE TITLE
[Minor] On Firefox, the breadcrumb bar is a pixel misaligned for the active component

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#290]
![screen shot 2015-11-18 at 1 51 30 pm](https://cloud.githubusercontent.com/assets/316479/11250660/83d1c2ea-8dfb-11e5-9642-91e57e39e124.png)

**Comment by remomueller** [comment]
@mrueschman can you check this in IE on staging? I put a place in for Firefox, and am hoping that it didn't have a negative impact on the display in other browsers. Thanks!

**Comment by mrueschman** [comment]
Looks OK to me in IE in a quick click-through!

**Comment by remomueller** [comment]
Thanks, closing issue!
