### ISSUE TITLE
Allow schedules to be generated at time of randomization

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#292]
From MikeM:

> Going through our protocol and looking for loose ends and wanted to get a reality check with you on generating and printing visit schedules based on randomization date. As its currently listed only the one unblinded RA will be able to access and print a visit schedule to give to a ppt due to possible unblinding caused by an existing AT surgery visit.  Since we haven’t really discussed this need my two questions are:
>Is this realistic in Slice? Being able to print out a list of in-window dates immediately after randomization that can be printed/emailed?

**Comment by mrueschman** [comment]
I'll move this into 0.33.1, but it can be shifted later if need be. A one day implementation might be sort of crude.

I would give it a good chance this might be asked about on Tuesday, since I will be focusing time on the process of randomizing a subject.

Giving this a quick thought, this is what comes to mind:

On a given randomization scheme, allow the user to setup an optional "schedule" or "timeline" that basically consists of:

1. Events (may wish to call something different because we already have Events)
2. Time offset from randomization (e.g. 30 days, 3 months, 1 year)
3. Windows (e.g. +/- 2 weeks)

Then at the time of randomization, display a table that lists out all the key dates for events and the in-window range (start date and end date.. this text could be less emphasized).

I don't think these schedules would really need to be stored in any way, it seems like they could be generated on the fly and set in stone at the time of the randomization. If events, offsets, and windows change later.. I don't think these changes would apply retroactively.

Anyway, we can start pondering this!

**Comment by remomueller** [comment]
Would it make sense to have this be the start of task lists that can be marked as completed, and that send out notifications when they start being due? The tasks could include the optional windows as you've described as well.

**Comment by mrueschman** [comment]
Maybe.. inevitably the question will arise.. shouldn't/couldn't this task list be linked with the Events I am already creating for the subject as they progress through the study?

**Comment by remomueller** [comment]
Tasks could be part of either process. Events could have associated tasks, as well as randomizations. Randomization tasks would be along the lines of, "Be sure to schedule a followup visit during this time window", and an event task could be "Call to remind participant of upcoming visit"
