### ISSUE TITLE
Filtering by randomized subjects on Subject vs Design Report

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#294]
From @mcailler:

> Now that we have randomization integrated into Slice, is there a way to create a report that’s filtered to only randomized subjects? Would be useful for data checking.
> Ideally, I would just want it as a filtering option on the Subject vs. Design report, in addition to 'valid' and 'test'

**Comment by mrueschman** [comment]
Easily doable with a data export. Maybe in the future we will enhance Reports generally to include additional modes of filtering. Closing this issue.
