### ISSUE TITLE
For public surveys / handoffs, do not show missing options upon first display

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#296]
However, if the form is submitted and an error is thrown for required fields not being completed, show the missing options upon form reload.

Scenario: Tablet is handed off to participant; participant fills in most of a questionnaire but does not want to answer a certain question (missing options are not shown); participant tries to submit and move onto next form; Slice throws error saying questions have not been filled out; participant can now select newly shown option (e.g. "Prefer not to answer").

**Comment by remomueller** [comment]
@mrueschman Did you want this in v0.33.0?

**Comment by mrueschman** [comment]
.. sure, if the initial implementation is fairly straightforward?

I wouldn't want to invest a lot of time in it because I still have an inkling we are going to run up against the tension point of "how can participants forego certain questions" at a future point in time. When that occurs, we may need to come up with a modified solution.

**Comment by mrueschman** [comment]
Closing this for now. The proposed solution still seems a bit convoluted and we haven't encountered the anticipated issue thus far. If issues start cropping up when on handoffs we might consider new workarounds.
