### ISSUE TITLE
Allow ranges on numeric/integer to be input/edited from Design editor

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#298]
It's not possible to "Edit Ranges" for integer/numeric fields (e.g. height/weight) -- only dates.

![image](https://cloud.githubusercontent.com/assets/707167/11792299/6510363e-a273-11e5-94ed-2e225269dda1.png)

**Comment by remomueller** [comment]
You may be able to do this currently when editing a variable directly if you need a workaround.
