### ISSUE TITLE
"1 to 40 of 866" counters are inexplicably large in IE

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#302]
IE11:

![image](https://cloud.githubusercontent.com/assets/707167/11841895/2c5dbb70-a3ce-11e5-9280-dfe52ca389d2.png)

Chrome:

![image](https://cloud.githubusercontent.com/assets/707167/11841926/54b96e16-a3ce-11e5-9009-d3e376f7dc6e.png)

**Comment by remomueller** [comment]
Turns out the CSS3 `initial` keyword isn't supported in IE: http://stackoverflow.com/a/16019352/1611947

**Comment by remomueller** [comment]
@mrueschman the fix for this should be live on staging. Can you take a look at it in IE? Thanks!

**Comment by mrueschman** [comment]
Yes, much better now!

**Comment by remomueller** [comment]
Thanks!
