### ISSUE TITLE
Primary menu not showing up in IE (?)

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#303]
Radu sent this screenshot; we will gather more information and try to reproduce:

![image](https://cloud.githubusercontent.com/assets/707167/11842272/a997d664-a3d0-11e5-953a-172ef5245cda.png)

**Comment by mrueschman** [comment]
Looks like a certificate error that VA workstations are experiencing. Maybe we should explore some sort of fallback/alternate method of making the main project navigation available when a strange occurrence like this pops up. @mcailler

**Comment by mrueschman** [comment]
This is happening on a new Windows laptop in IE at the Children's Hospital of Philadelphia (PATS recruitment site) as well. Does not occur in Chrome on the same machine.

Higher priority to figure out a workaround?

**Comment by remomueller** [comment]
Are you seeing any errors in IE (yellow warning sign)? :warning:

**Comment by mrueschman** [comment]
I'm not -- I turned on the status bar and poked around in the Developer Tools.

**Comment by remomueller** [comment]
Does it show any glyphicons (small icons) on other pages?

**Comment by remomueller** [comment]
One other question, if you can't see icons in Slice, can you see them in the same browser on the NSRR?

**Comment by mrueschman** [comment]
Oh wait, here's what I get: ![slice_ie_chop](https://cloud.githubusercontent.com/assets/707167/12175738/dfdfa7fc-b531-11e5-8692-1e67ae320325.png)

**Comment by mrueschman** [comment]
![nsrr](https://cloud.githubusercontent.com/assets/707167/12175774/0e6e77ec-b532-11e5-86cc-059a37f3091b.png)

**Comment by mrueschman** [comment]
![nsrr_dataset_page](https://cloud.githubusercontent.com/assets/707167/12175809/372f1678-b532-11e5-928e-90babd6acd4d.png)

**Comment by remomueller** [comment]
Does double clicking "SCRIPT###" show any additional information?

**Comment by mrueschman** [comment]
This page opens: https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k(VS.WebClient.Help.SCRIPT16389)

**Comment by remomueller** [comment]
Ok, should have enough to go on, will help to have a local machine to reproduce this on though.

**Comment by mrueschman** [comment]
I will be playing with different machines throughout the day -- I'll see if anything varies. My IE8 laptop (from BWH) on the CHOP wireless here has no troubles.

**Comment by mrueschman** [comment]
Update: The glyphicons work on IE 11 on the second laptop I got to use today. Both machines are on the same wireless network, the only discernible difference seems to be with the security settings. The CHOP machine is more locked down (e.g. requires admin to login upon installing any new software) and the UTexas machine seems open (local administrator rights).

**Comment by remomueller** [comment]
Is this related: http://stackoverflow.com/a/25304239/1611947

> The Problem was, that somehow my IE went in a certain security state, in which the font download was disabled.
> So I changed the Custom level of the "protected Mode" - you can find that in the Security Tab of the Internet Options Menu.

**Comment by mrueschman** [comment]
Seems likely. I will take a gander at this setting on the laptops.

Here's a recent comment that seems pertinent: http://stackoverflow.com/a/32832762

**Comment by remomueller** [comment]
@mrueschman I changed the menus to be text only, and removed the icons. We can modify more if changes are needed.
