### ISSUE TITLE
When deleting adverse event, change notification to say "deleted" instead of "destroyed"

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#304]
https://www.dropbox.com/s/m5irfqv9o81mjqj/Screenshot%202015-12-16%2018.58.56.png?dl=0

![](https://cloud.githubusercontent.com/assets/316479/12620214/53d4c8b0-c4e9-11e5-93a4-71ab5343eee0.png)

**Comment by remomueller** [comment]
This is pretty common, should I replace all instances of this?

adverse_event_comments
adverse_event_files
adverse_events
block_size_multipliers
categories
randomization_schemes
randomizations
stratification_factor_options
stratification_factors
treatment_arms

**Comment by mrueschman** [comment]
Yeah, let's do all of them!
