### ISSUE TITLE
Simplify subject index -- don't show all events as columns

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#310]
This may exist elsewhere, but I couldn't find it at a glance. We have discussed this before. Spanning all the events out on the subjects kills the overall usability of the page, so I think the listing needs to be condensed/reworked somehow (particularly for PATS).

![image](https://cloud.githubusercontent.com/assets/707167/12041956/49c27cde-ae44-11e5-882c-11da1c81ee77.png)

**Comment by mrueschman** [comment]
Another thought: For Site Editors, the "Site" column isn't useful and could be removed.

**Comment by remomueller** [comment]
What columns should be shown as an end result? (with site removed for users who are only on one site?)

**Comment by mrueschman** [comment]
Maybe a "Randomized" column -- some sort of indicator of whether they've been randomized or not.

Most Recent Event column? 

Most Recent Sheet column?

I envision a pretty simplistic table. Other ideas: number of AEs; subject created at; subject last updated at (like most recent activity of some sort).
