### ISSUE TITLE
Stratification factors should sort themselves alphabetically

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#312]
![image](https://cloud.githubusercontent.com/assets/707167/12146065/b8bda5b6-b45f-11e5-9b94-cd173127a540.png)

"BMI Percentile Category" needs to get in line!

**Comment by remomueller** [comment]
Should the ordering of values also be done (ex: BMI percentile should be 1:, then 2:)?

**Comment by remomueller** [comment]
@mrueschman, should the values also be ordered alphabetically?
