### ISSUE TITLE
When a Site editor adds a new subject, don't show or pre-fill Site field

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#315]
From Subject Index -> Create Subject..

![image](https://cloud.githubusercontent.com/assets/707167/12148879/d7eb6824-b46e-11e5-8e46-ead63913529c.png)

![image](https://cloud.githubusercontent.com/assets/707167/12148885/dce08f58-b46e-11e5-8d47-4b48a9b836d4.png)

**Comment by remomueller** [comment]
Essentially this should be, don't show the site field for users on only one site?

**Comment by mrueschman** [comment]
Yes, that sounds right!
