### ISSUE TITLE
Possibly revamp/hone the validation/checking that goes on at time of randomization

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#316]
This always comes up: The fact that site staff may have to re-enter / verify the stratification factors at the exact time of randomization. It is imperative that mistakes not be made at this stage, so coordinators/investigators are always asking about double-checking/validation/confirmation.

I wanted to get an issue on the books to keep this in mind when we pick back up with Slice. 

From a related email thread:

> I was going to bring this particular issue up with Remo again – i.e. either 1) having the stratification factors pulled from elsewhere (i.e. other Designs/Sheets) or 2) having each individual factor be sort of “double checked” against entry that has occurred previously.
> 
> Right now there is a rudimentary system in place where the Randomization cannot occur in Slice if a single criteria (i.e. variable on another Design) is not met (i.e. has the value specified). Maybe this could be embellished a bit to make #2 above more robust.

**Comment by mrueschman** [comment]
Perhaps allow each stratification factor to be linked to variable, whose value would be pulled for a given subject at the time of randomization.

**Comment by remomueller** [comment]
In discussing, I think we could do these similar to calculated variables, so that you'd provide a formula along with the stratification factor so that you could essentially compute a value from multiple variables. We'll have to figure out how to handle the subject having multiple (or missing) values for certain variables though.

**Comment by mrueschman** [comment]
Reference the "Child Information Worksheet" in the PATS project in production.

![image](https://cloud.githubusercontent.com/assets/707167/13008694/dae30032-d165-11e5-9e65-3b5254ef49c6.png)

`ciw_age_years` represents the child's age in years.

`ciw_age_cat_for_randomization` is the calculated field below it, using this calculation:

```
(ciw_age_years > 2 && ciw_age_years < 6) ? 1 :  (ciw_age_years >= 6 && ciw_age_years < 10) ? 2 : -9
```

This calculated field should then be referenced from the "Age Category" randomization stratification factor, where the "1" and "2" values will align:

![image](https://cloud.githubusercontent.com/assets/707167/13008715/f607a1d8-d165-11e5-9618-857424747b2e.png)

If the factor is tied to another variable (or just the calculation itself), then this stratification factor could **only** be set in this fashion (i.e. can't be set manually). In cases where the calculation was not resolving into a "1" or a "2", we would need, in some manner, to alert the user as to why randomization is being thwarted at this point (e.g. some reference to the calculation and/or Child Information Worksheet variables needing to be filled in).
