### ISSUE TITLE
Improve the efficiency of exporting data by reducing number of database hits

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#320]
To do this, the export method has to be reworked to pull out data by variable (column) instead of by subject (row).

This way, the variable responses can be processed and formatted at once per variable (instead of once per subject per variable). Since this will export each variable as a row, the resulting matrix has to then be transposed to match the current format.

- [x] Sheet Export
- [x] Grid Export
- [x] Fix overall progress counter
- [x] Remove Checkbox "aggregate" columns, these may be combined via SAS or R at a later point

**Comment by remomueller** [comment]
@mrueschman I've finished the updating the exports. Can you test the SAS code generated on staging to see if everything is working as expected? Thanks!

**Comment by mrueschman** [comment]
I went through a couple exports and, on their face, everything looked intact. The SAS imports completed successfully and all the variable label/formats seemed to be in place.

**Comment by remomueller** [comment]
Great thanks, I also ran the R import script and it appeared to work. We'll have to get an R expert to make sure it's working as intended though. Closing this issue then, if new errors come up, we can open new issues for those. Thanks!
