### ISSUE TITLE
Add ability to enforce ID formats when subjects are being created

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#321]
We'll want to have the ability to make sites conform to subject IDs of a certain length/format.

For instance, site 1 on PATS would only be able to create IDs in the range of 10000-19999.

**Comment by remomueller** [comment]
Let's say we also wanted it to start with an S, so S10000 to S19999. IN this case you might write the format as: `S1%d%d%d%d`. If we used regex it might be `S1\d{4}`.
