### ISSUE TITLE
Add ability to copy a project wholesale

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#323]
For the PATS Certification project, for instance.

**Comment by remomueller** [comment]
Instead of wholesale, I would recommend that this only items needed during project setup. For example, designs, events, invited users, and project settings. This would be more similar to using a project as a template for another project.

**Comment by mrueschman** [comment]
Yeah, this is probably more of what I was intending. All the things needed to prop up the project and have it ready to accept its first subjects/sheets.

**Comment by remomueller** [comment]
Copied project is now available on staging for testing
