### ISSUE TITLE
Tweak how AE forms show up for entry

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#324]
Possibly put them in-line with the AE comments to begin with, and make the "Forms" tab more intuitive to use/navigate.

**Comment by remomueller** [comment]
- [ ] Redesign the forms tab itself

**Comment by remomueller** [comment]
Hi Mike, We may be able to remove the forms tab completely if needed, "attached" forms could be put up right at the top of the AE history (as well as inline), and the "Would you like to add more forms" could be displayed to only list forms that haven't been started or filled out yet. Thoughts?

**Comment by mrueschman** [comment]
Sounds like a worthwhile thing to try. The one thing to keep in mind is that certain forms may need to have multiple copies entered on a single AE. For instance, multiple "Health Care Utilization Encounter" sheets for a single AE event.
