### ISSUE TITLE
Odd behavior when scrolling in large dropdown lists

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#328]
Evident in PATS "Staff ID" type field, e.g. https://tryslice.io/projects/pats/designs/187

Scrolling through the long list in the dropdown and then moving mouse will sort of "jump" you to the item you had your mouse on previously. This could make hunting/pecking with the mouse + scroll wheel alone kind of difficult.

(May be difficult to pin down!) Putting in 0.33.0, but not essential.

**Comment by mrueschman** [comment]
Also is quite evident when building custom Reports on projects with long variable lists for a given Design. Choosing a variable that is in the middle of the variable list can become quite difficult with the mouse.

**Comment by remomueller** [comment]
Looks like it's related to a bug in jQuery 2.2.0 that hasn't been fixed yet and is related to scrollTop. I've put in the workaround suggested in the Chosen repository.
