### ISSUE TITLE
For time durations, use full words in description below after entry

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#337]
![image](https://cloud.githubusercontent.com/assets/707167/13018780/b236a2b8-d199-11e5-82b1-958a1248de8c.png)

**Comment by remomueller** [comment]
I'm assuming you'd want this to look something like this:

1 hour 5 minutes 5 seconds, and 2 hours 1 minute 0 seconds, etc

**Comment by mrueschman** [comment]
Yeah!
