### ISSUE TITLE
Make printable (easily disseminate-able) schedules at time of randomization

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#346]
Mindset: Something that the coordinator could hand to the subject soon after hitting the "Randomize!" button.

This was requested by CHOP long ago for PATS -- issue #292 was opened as a means to get this started.

I *may* have promised on the Slice demonstration call that we would have something more concrete by the time of the first randomization (probably April), so I wanted to make an issue to keep in mind when we move past 0.34.0.

**Comment by remomueller** [comment]
Do we have an example word document or PDF to go off of?
