### ISSUE TITLE
Unblinded site editors should receive notifications about AE activity/updates from their site

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#347]
Currently only project-level folks get the notifications, but it will be nice for sites to be notified when a DCC Project Manager comes in and adds a comment / asks a question.

**Comment by remomueller** [comment]
Changing this to project members (editors and viewers), and the subject's site members (editors and viewers) to receive notifications. Also initial email is sent to the group, minus the initial person reporting the AE.
