### ISSUE TITLE
Allow range constraints to reference other variables

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#349]
One idea being: 

> 1. Date adverse event started: _____
> 2. Date adverse event resolved: _____

Question 2 can never have a date value that comes before Question 1 (they could be equal).

**Comment by mrueschman** [comment]
Update: We should be able to get at this issue another way through Checks. See #449

**Comment by remomueller** [comment]
@mrueschman do the current version of checks allow this to be done?

**Comment by mrueschman** [comment]
I don't think so, since we cannot compare a variable to another variable?

**Comment by remomueller** [comment]
So taking a look at this, it may be possible to create a rule (or calculation perhaps) at the bottom of a design that would allow this to be captured on the sheet level. Other ideas would be adding the ability to add custom rules to the sheet errors checker, which is similar to what checks do, but instead do it by expression instead. Closing this issue, but we can revisit later if we want to focus on one of these approaches.
