### ISSUE TITLE
Create public library of design templates

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#364]
These design templates can be copied to existing projects as long as the variable/domains don't overlap with existing variables in that project. This will replace design JSON imports.

A new role of library curator may be needed.

**Comment by mrueschman** [comment]
Note: Recently got a request to copy a couple designs to a new project. A public library would have been great. :+1:

**Comment by remomueller** [comment]
Question, who can contribute to the public library, anyone (by user/by project?) Should designs in the library be actual designs on projects, or something separate (more template like?)

**Comment by mrueschman** [comment]
I think something separate (template-like), easily "importable" into a project of your choosing, and/or maybe even "downloadable" in some genericized format(s) (PDF, JSON). Not sure about going from an existing project to the library; clearly it would suck to have to "remake" a huge form if it already exists, so having a way to send/submit existing designs to the library would be nice.

I think the main library would be curated to some degree by Slice administrators, though anyone could create and submit new forms to it.

**Comment by remomueller** [comment]
cc @mrueschman, I'm closing this issue as we have some of the items in place now for the next release. We can break up the rest of the details needed for this into new issues across the next several releases. Thanks!
