### ISSUE TITLE
Add ability to send links to external who need to complete some sort of AE review

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#370]
For PATS, we have a Medical Monitor and DSMB contacts who periodically will need to review data on Adverse Events and do some sort of commenting / sign-off on the AE in Slice. We do not want these external project contacts to be Slice users, so we need a way to generate a link from within Slice that could be emailed, clicked on, show the components of the AE (like the AE Report Form, a sheet entered by the site), and then have the external person fill in a couple fields and/or a comment box. 

We will discuss this more amongst the PATS team as we decide upon an implementation.

**Comment by remomueller** [comment]
@mrueschman, I'm removing this from the 0.38.0 milestone, but we can readd the functionality in a future release when we've finalized the workflow.

**Comment by remomueller** [comment]
Functionality is there, however has been disabled. If needed in future, we can create a new issue. Closing current issue.
