### ISSUE TITLE
On report builder, cannot click variables to remove them or change date distribution

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#384]
![image](https://cloud.githubusercontent.com/assets/707167/14926991/3bf6a060-0e1d-11e6-93b9-046e78c4635c.png)

Variables can be rearranged between rows and columns, but clicking on them does nothing (to delete, for instance).

**Comment by remomueller** [comment]
It appears I may have moved the following method: 
/projects/$project_ID/edit_filter?variable_id=site&missing=0&axis=row&by=
