### ISSUE TITLE
Data dictionary 'variables' should have the individual checkbox variables listed

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#387]
Presently checkbox variables come out in the data dictionary as a single row in the 'variables' CSV. In the exported data and SAS scripts, the individual component variables are listed and correctly imported.

Replace the parent checkbox variable with all its component parts in the data dictionary. (It appears as if the MyApnea data export does it in this fashion.)

**Comment by remomueller** [comment]
So don't include it as a multichoice variable, but instead split as several "radio" choice variables?

**Comment by mrueschman** [comment]
Yes, split it into its component parts.. e.g. "demo_race__1", "demo_race__2" , "demo_race__3" instead of just "demo_race". I'm fine with leaving each of the component variables listed as the `checkbox` type all pointing to a shared domain.
