### ISSUE TITLE
Create Report that gives sheet validation messages within Slice (Range checks and expected calculated values)

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#40]
**Original Title** Calculated fields do not update when updating options on a variable that the calculated variable depends on

Calculated variables should be verified server side, also possibly provide a view to check for discrepancies.

**Comment by remomueller** [comment]
I think we can revisit this in a different way. I suggest that we create a in application sheet report that goes through existing sheets and computes validation of variables and values that could have become invalid after ranges were added after data collection. This report could also recompute and compare the calculated field with the expected result. Would also help find issues like that reported in #423.

**Comment by remomueller** [comment]
Removed this from current milestone.

**Comment by remomueller** [comment]
@mrueschman in order to start working through some of these older issues, I'm looking at this one as the oldest one. I think having a check that's run on our job server may be a good place to start with this. Ideally we'd generate a task that runs through variables on a sheet, and checks ranges/calculations/stored type (compared to variable type). The front end servers would then provide a check list style of sheets with "questionable" values that could be reviewed.

**Comment by mrueschman** [comment]
That sounds good to me. Seems like a continuation of your thought from 2016, and a good use of the job server since this is definitely something that wouldn't need to be run in real time.
