### ISSUE TITLE
When setting a sheet as missing, also save who set the sheet as missing

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#409]
While the audits track this, it's not tracked on the sheet itself.

**Comment by mrueschman** [comment]
When doing this, you might look to how these are reported in "Activity" as well:

![image](https://cloud.githubusercontent.com/assets/707167/16042624/af9db584-3209-11e6-87a7-326b1242a9b7.png)

Replace "Public user" with the user's actual name and perhaps more clearly delineate that a *missing* sheet was created.

**Comment by remomueller** [comment]
That would resolve itself if the user is initially captured as creating the sheet. I'll have to see if it's possible to make it state that a sheet was set as missing though in this view.
