### ISSUE TITLE
Allow site "short_names" to be set for sites

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#415]
While the `short_name` is computed dynamically, it would be useful to allow an @mrueschman to be able to set better `short_name`s that better reflect the sites' abbreviations.

**Comment by mrueschman** [comment]
What do you think about adding a "site code" of sorts as well?

For PATS these codes would be the site #s, i.e. 1 through 5.

Theoretically you could then use this in the SAS export to more efficiently output the site. Output the site codes to the raw files and then use a variable format to apply the full site names.
