### ISSUE TITLE
Add advanced search to subject index

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#425]
Question: How do I filter the subject list to just those who have consented?

Drill down to individual variables with specific values.

**Comment by remomueller** [comment]
Would you prefer `is:consented` or `consented:yes` and `consented:no` or with values instead of yes no?

**Comment by remomueller** [comment]
And multiple values like this: `consented:1,2`?

**Comment by mrueschman** [comment]
I think "is:consented" is pretty cool. 

Just curious, how do we define what "consented" is? Maybe the multiple values thing would happen at the "definition" stage and not so much at the search? Dunno.

**Comment by remomueller** [comment]
We could have `is` represent value of `1` and `not` as a value of `0` for variables. We wouldn't be defining consented, it would work like this for all variables (using the variable name). If we did this though, we would have to also go with `2:consented` and `3:consented` if there were other options, to stick with `value:variable` format.

**Comment by remomueller** [comment]
We could also have `is` and `not` be special cases for the parsing format.

**Comment by remomueller** [comment]
Note to myself `has:ae` `is:randomized` `has:comments` `has:file`

**Comment by remomueller** [comment]
Here's a thought, the checks in the system currently have a slug, so you could technically make a check for called "consented". You could then use this as a shortcut on the subjects index and type: is:consented, which would load the logic for the check itself.
