### ISSUE TITLE
Tweak how Subject Code "errors" are shown from Randomization page

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#434]
This topic probably relates to #371 in a way. 

It might be nice to warn users ahead of time when an errant (i.e. either non-existent or non-randomizable (?)) Subject Code is entered at the time of randomization. 

- [x] Show subject code not found, instead of "NEW"
- [x] Lock subject code if launching randomization from subject page

**Comment by remomueller** [comment]
Checking whether or not they are randomizable during the autocomplete process may be a bit expensive, although it does compute all their stratification factors. Would they be "ineligible", "not fully eligible"? Currently it shows "Eligible" and "Randomized".
