### ISSUE TITLE
Allow filtered lists of sheets to be further sorted

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#444]
E.g. from an already filtered type list, after clicking on a count from a Report:

https://tryslice.io/projects/pats/sheets?design_id=476&f%5B%5D%5Bend_date%5D=&f%5B%5D%5Bstart_date%5D=&f%5B%5D%5Bvalue%5D=1&f%5B%5D%5Bvariable_id%5D=14299&order=sheets.subject_code

Clicking to sort on something like "Subject" actually loads up the entire Sheets index.

**Comment by remomueller** [comment]
The design was intentional at the time to make sure users can reset filters and view a complete list of subjects. The actual filter system itself needs to be reworked and simplified, which would greatly help with this as well.
