### ISSUE TITLE
Simplify initial project creation

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#485]
Creating a project should simply ask for a project name.

After the project is created, a "settings dashboard" should allow different modules to be enabled and disabled (perhaps with one-click buttons/switches).

The project logo could be uploaded on this separate interface (instead of through the current form with every option).

- [x] Initially ask for project name
- [x] Make sure to strip spaces from project name
- [x] Go to setup where modules can be disabled enabled
- [x] Allow sites to be added
  - [x] Allow creation of multiple sites at once as well as "Skip this step"
- [x] Allow users to be invited
- [x] Modules should be single page
  - [x] Adverse Events
  - [x] Blinding
  - [x] Randomizations
  - [x] Data Locking module
  - [x] Tablet Handoff module
- [x] Make sure "trivial"/"advanced" settings can continue to be updated as well
  - `URL Slug`, `Description`, `Disable Daily Digest`, `Hide Values on PDFs`, `Tablet Handoffs`
  - [x] "Subject Code name" as editable on newer projects
  - [x] Remove `Collect Survey Participants Email` #481
  - [x] Remove editing `Logo`

**Comment by remomueller** [comment]
@mrueschman I'd like to discuss the "Subject Code name" attribute when setting up projects, is it being used, do we need to keep it, can we say "Subject Code" less often elsewhere to minimize the impact?

**Comment by mrueschman** [comment]
I don't think it has been used much. I wonder what the one name would be.. the [FDA Good Clinical Practice guide](http://www.fda.gov/downloads/Drugs/.../Guidances/ucm073122.pdf) calls it "Subject Identification Code":

> 1.58 Subject Identification Code: A unique identifier assigned by the investigator to
each trial subject to protect the subject's identity and used in lieu of the subject's name
when the investigator reports adverse events and/or other trial-related data.

**Comment by remomueller** [comment]
Ok, I'll remove it as a configurable setting for now, but maintain it for older projects.
