### ISSUE TITLE
Dashboard should get Action buttons to change project favorites.

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#486]
This should be an actions button with a dropdown, similar to how sheet show page shows actions.

Additionally, may want to remove extra numbers/options on Project Dashboard.

**Comment by remomueller** [comment]
@mrueschman is it still useful to have the number of subjects on the dashboard, I feel like we can have some type of graph or chart that displays information about each project visually somehow. Activity? Total data points? Online users?

**Comment by mrueschman** [comment]
I always like seeing the number of subjects and think I'd prefer it above other metrics like data points / online users. Seeing supplemental things like activity could be cool, though.

**Comment by remomueller** [comment]
OK, thanks, I also imagine if I did add the other indicators, they would not take up much space (more like inline graphs).

**Comment by remomueller** [comment]
Closing this issue, made a new issue #501 for displaying project activity.
