### ISSUE TITLE
Remove "indented underneath" visibility option

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#537]
Essentially remove `['Above - Indented', 'invisible']`, and keep `['Inline', 'visible']`, and `['Above - Full', 'gone']`

This could then be simplified to `Inline` and `Underneath`, or Layout `Horizontal`, `Vertical`

**Comment by remomueller** [comment]
cc @mrueschman, which of the above simplified naming convention would you like to see?

**Comment by remomueller** [comment]
Note that horizontal layout still falls back to vertical layout on mobile devices.

**Comment by mrueschman** [comment]
I like "Inline" and "Underneath".

**Comment by remomueller** [comment]
Ok, thanks!

**Comment by remomueller** [comment]
```ruby
Variable.where(display_name_visibility: 'invisible').update_all(display_name_visibility: 'gone')
```

**Comment by remomueller** [comment]
Note to change `display_name_visibility` to `layout`
