### ISSUE TITLE
Upon filtering a list of variables, trying to advance to next page will clear filters

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#555]
![image](https://cloud.githubusercontent.com/assets/707167/21620311/b335c8b4-d1c1-11e6-89d1-e90fc6477204.png)

**Comment by mrueschman** [comment]
Note: Happens on Domains index, too. Perhaps it occurs everywhere?

**Comment by remomueller** [comment]
It's actually on any index that references the `_per_page.html.haml` partial.
