### ISSUE TITLE
Display meaningful stats for dates and times on Overview Reports

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#559]
From the PATS PSG Report

![image](https://cloud.githubusercontent.com/assets/707167/21772879/07e7982c-d65b-11e6-98df-382c08a05cb3.png)

For dates and times the minimum and maximum would be useful to know.

- [x] Time of day min and max stats
- [x] Dates min and max stats

**Comment by remomueller** [comment]
This has been partially completed for times with #523.
