### ISSUE TITLE
Display variable units on overview report

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#560]
The "units" (showed as suffix during entry) are not shown on Overview reports, though this would be useful when looking at continuous variables.

![image](https://cloud.githubusercontent.com/assets/707167/21773048/922f4958-d65b-11e6-94ff-fa86f8f6d60b.png)

**Comment by remomueller** [comment]
Also, clicking links to filters should provide the units that are being filtered to. ex: oz and in for imperial units
