### ISSUE TITLE
Allow clock times to be used in calculations

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#567]
Would be useful to create Checks that combine wake times with bed times and look for possible AM/PM confusion among respondents. This happens a lot!

One consideration: Store clock times as "seconds from midnight" (e.g. 43200 = 12:00 p.m.) Might open other options.

**Comment by remomueller** [comment]
Hi @mrueschman, can you check to see if clock times work in calculations as you would expect?

**Comment by mrueschman** [comment]
Threw up some tests for "time in bed" on staging, they seem to work well at a glance!

https://staging.partners.org/tryslice.io/projects/pats/designs/481

**Comment by remomueller** [comment]
Great, thanks for checking!
