### ISSUE TITLE
Allow designs on events to be conditional based off of previously entered values

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#569]
Ex: isaac_score_greater_than_5==1
If this is true, then all of the phone call visits should also require "Asthma Severity Survey"
the ISAAC (Int'l Study of Asthma..) at Baseline.

**Comment by mrueschman** [comment]
In plainer terms: At baseline, a breathing-related sheet (ISAAC) is filled out and a "global wheezing score" is calculated. If the score is above a certain threshold, subjects are asked the Asthma Severity Survey at the baseline event and subsequent events (phone calls mainly).

**Comment by mmorrical** [comment]
If isaac_score_greater_than_5==1 at _either_ baseline or 6 month then all follow-up calls and 6M/12M visits need the asthma form. 

I believe we have to collect the Asthma Survey at the 12M visit even if the ISAAC collected then is the only instance of a score >5, but chances are this may never happen.

**Comment by remomueller** [comment]
Basically, certain events will only show a design if a certain condition is met, the condition is based on an "event", "design", "variable", "value" pairing. (With event being optional). Probably be useful to create a method for entering these on the subject level, ex: get value for subject given these conditions, which can return an array (hashes?) or single value based on where the response if found.
