### ISSUE TITLE
Colors for permuted block randomization lists could use a change in night mode

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#592]
![image](https://cloud.githubusercontent.com/assets/707167/23316445/738acdea-fa98-11e6-9f70-8e2b8fbf8413.png)

Gray text is a bit hard to discern on the purple and gray backgrounds.

**Comment by remomueller** [comment]
Permuted blocks now use four colors (red, blue, green, and amber) across all themes. Night theme has a darker version of these. Links for randomizations are white, with non-randomized portions as a darker color.

**Comment by remomueller** [comment]
![screen shot 2017-03-07 at 5 17 10 pm](https://cloud.githubusercontent.com/assets/316479/23680635/f48b2574-0359-11e7-9b2d-e3eea6e1377f.png)
