### ISSUE TITLE
Fix night mode coloring for duplicate sheets on event

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#593]
![image](https://cloud.githubusercontent.com/assets/707167/23519284/59e535b4-ff44-11e6-9920-8ccda0fdba0b.png)

**Comment by remomueller** [comment]
@mrueschman, this styling is intentional, the tables have alternating row colors, and the "highlight" color in the dark mode is the yellow you are seeing there (with the darker version being the alternating row effect). What about it did you want changed?

**Comment by remomueller** [comment]
Changing this issue to address the idea that some events can have duplicate sheets and it's not an "issue", i.e. the sheets shouldn't be marked as duplicate. ("Allow Duplicates").

**Comment by remomueller** [comment]
Here's a sample of the changes made. In this case, the Screening even has the "PSG Report" set as "Ignore Duplicates" while the CIW is still set as "Highlight Duplicates" (default).

![screen shot 2017-03-09 at 4 44 28 pm](https://cloud.githubusercontent.com/assets/316479/23772100/c3e73dc4-04e7-11e7-96c5-7ecb68858f49.png)

**Comment by remomueller** [comment]
I also improved the readability of the highlighted rows text in night mode, and added the sheet creation date for duplicate sheets to be able to tell them apart slightly better.
