### ISSUE TITLE
Add 'varnum' to proc contents statements in SAS script

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#608]
Change any use of PROC CONTENTS as follows.

Current:

> proc contents data=slice_grids;
> run;

New:

> proc contents data=slice_grids varnum;
> run;

This orders the SAS output by variable position instead of alphabetically (by variable name). This is my preferred style.

**Comment by remomueller** [comment]
@mrueschman is this only for slice_grids, or is for the other proc contents as well?

**Comment by mrueschman** [comment]
For both 'slice' and 'slice_grids'.
