### ISSUE TITLE
Consider alternatives to speed up and make AE Export more efficient

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#614]
Re: https://github.com/remomueller/slice/issues/266#issuecomment-154113591

Right now in PATS including "CSV Labeled" gives you a 15+ minute export wait time. For AEs, however, exporting only the AE-related sheets would be optimal.

(Perhaps also use this as a kicking off point for speeding up exports generally.)

**Comment by remomueller** [comment]
- [ ] AE Filter should only export sheets related to AEs

**Comment by remomueller** [comment]
Close in https://github.com/remomueller/slice/commit/bc95058fc114f6b7c4100f1cf396935ccd464518#diff-ce1ab4ce5dfeedbdd36ddf79362e4a10
