### ISSUE TITLE
When editing a design, the Reorder button is shaded from the start

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#665]
If you edit a design straightaway, the upper-right looks like this:

![image](https://user-images.githubusercontent.com/707167/37781012-4c9107ce-2dc6-11e8-85e5-b85ade961cf9.png)

If you click Edit mode, the page stays the same (since already editing), but buttons change to following:

![image](https://user-images.githubusercontent.com/707167/37781045-5d2e4754-2dc6-11e8-989b-4e80707668a9.png)

Should Reorder mode be unshaded and then allow for a "highlight" effect when you rollover it? And Edit should be shaded when you first go into edit mode?

**Comment by mmorrical** [comment]
Agreed. It does seem a little odd that it doesn't visually indicate you are in edit mode immediately. I hadn't experimented with the edit/preview toggle yet but it appears to be a great QOL improvement.

**Comment by remomueller** [comment]
@mmorrical @mrueschman, I'm supposing this issue is supposed to be open, right?

**Comment by mrueschman** [comment]
Yeah!
