### ISSUE TITLE
AM is cutoff in time entry fields

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#688]
![image](https://user-images.githubusercontent.com/707167/43144678-b558f7c8-8f2b-11e8-8a72-fe1a92b76d70.png)

PM is OK

![image](https://user-images.githubusercontent.com/707167/43144705-c112ca9e-8f2b-11e8-8779-cf7c77277c74.png)

**Comment by remomueller** [comment]
@mrueschman what OS/browser is this in?

**Comment by mrueschman** [comment]
Chrome 67, Windows 10
