### ISSUE TITLE
Revamp data checks

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#691]
Not sure if it would be a modification or rebuild, but I think we could take some lessons learned from the first iteration of check system and focus on something more intuitive for the next go-around.

![image](https://user-images.githubusercontent.com/707167/43718135-bc3f0830-9957-11e8-83a5-17d531e1a7f0.png)

**Comment by mrueschman** [comment]
For reference, REDCap has a "Data Quality" area where you can define "rules" that can be run both 1) on demand and 2) real-time during data entry.

Setup rule that diastolic can not ever be higher than systolic.

![image](https://user-images.githubusercontent.com/707167/43855177-d281592e-9b12-11e8-9533-15e0d75ee3f2.png)

Result when I try to save a form with violation.

![image](https://user-images.githubusercontent.com/707167/43855115-b16ffae2-9b12-11e8-9b02-1fa25ddb60e9.png)

**Comment by remomueller** [comment]
@mrueschman, I'll be closing this issue, but moving the other checks you've mentioned into individual issues.
