### ISSUE TITLE
Expand adverse event (AE) monitoring/reviewing system

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#692]
This may branch out into multiple issues, but thinking ahead for LOFT.

Initial (possible) items:

- Add role for "AE Reviewer/Adjudicator": user could login to system but only access AEs (and accompanying data/uploads) assigned to them for review. Ultimately these reviewers would have a specific sheet to fill out and save, at which point their work on a given AE would be finished.
- For users assigned AE reviews, generate reminder notifications and/or emails daily (?).
- Review/revise layout/presentation of AEs. Just looking at it now (after a long time away) there seems to be some places that could be styled/presented better.
- ~~Incorporate MedDRA as a special type of field, making categorization/lookup of AEs easier on staff. Maybe less error-prone, too.~~ Moved to #715. 

cc: @michellereid

**Comment by remomueller** [comment]
Moving to dedicated v69 release
