### ISSUE TITLE
Fix difficult to read text areas in night mode

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#693]
Variable show page (type/units):

![image](https://user-images.githubusercontent.com/707167/44097378-9aa6db08-9fab-11e8-892d-ef4effe49d47.png)

File attachment "Attach file" (button/text) and "Remove" text:

![image](https://user-images.githubusercontent.com/707167/44097398-a7996b14-9fab-11e8-9c3c-52900ac378ae.png)

**Comment by mrueschman** [comment]
![image](https://user-images.githubusercontent.com/707167/44419671-db957180-a549-11e8-84de-d8b4c4fadbe8.png)

**Comment by remomueller** [comment]
Thanks for putting these together, should get some tweaks for these in the next release

**Comment by remomueller** [comment]
@mrueschman even though this one is closed, if you find more like this, feel free to reopen this issue and provide the screenshots, the above are all set.
