### ISSUE TITLE
AE module tabs floating and not left-aligned

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#730]
![image](https://user-images.githubusercontent.com/707167/51695460-1ad05e80-1fd1-11e9-8c0d-7aa80a8c12e9.png)

![image](https://user-images.githubusercontent.com/707167/51695477-26238a00-1fd1-11e9-9b02-8102b27a3bd1.png)

**Comment by remomueller** [comment]
Closed by b3dfdf99abf75abf5c66bf050c3d626fdd609402.
