### ISSUE TITLE
Go directly to Preview Mode when clicking from Reorder Mode

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#738]
Situation: In Reorder Mode while editing a Design.

If you click "Preview Mode" it actually switches to "Edit Mode". Clicking Preview Mode again now gives the preview. Something I assume with how Edit/Preview toggle back and forth.

On a side note, do we need to include the word "Mode"? Should the top just say Edit | Preview .. Reorder?

**Comment by remomueller** [comment]
Hi, I was just thinking about these buttons recently when adding in the breadcrumbs for the next release. Would it be best to simply remove the preview mode completely (as the changes go live in edit mode currently anyways), and then rely on the show page to show the current state of the design? A preview mode may make more sense if we had an actual "publishing" process for the designs.

**Comment by mrueschman** [comment]
Removing the Preview mode sounds OK.
